stages:
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - .npm/
        - node_modules/
        - cache/Cypress

test:
    image: node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1
    stage: test
    before_script:
        - npm ci
    script:
        - export CYPRESS_validABTastyEmail="$validABTastyEmail"
        - npm run tests
    artifacts:
        when: always
        paths:
            - cypress/reports/html
            - cypress/screenshots
        expire_in: 30 days
    only:
        - develop
